default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ml_interview_platform_development

test:
  <<: *default
  database: ml_interview_platform_test

production:
  <<: *default
  database: ml_interview_platform_production
  username: ml_interview_platform
  password: <%= ENV['ML_INTERVIEW_PLATFORM_DATABASE_PASSWORD'] %>


