development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || "your_secret_key_base_here_development" %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || "your_secret_key_base_here_test" %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>


